[package]
name = "voting_contract"
authors = ["Satyam Bansal"]
compiler_version = ">=0.26.0"
type = "contract"

[dependencies]
# Framework import
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.34.0", directory = "noir-projects/aztec-nr/aztec" }
